import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CORE_REPO = "hegeldev/hegel-core"


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=ROOT)


def get_current_version() -> str:
    text = (ROOT / "installer.go").read_text()
    m = re.search(r'^const hegelServerVersion = "([^"]+)"', text, re.MULTILINE)
    assert m is not None
    return m.group(1)


def bump(version: str) -> None:
    current_version = get_current_version()

    installer = ROOT / "installer.go"
    text = installer.read_text()
    text = re.sub(
        r'^const hegelServerVersion = "[^"]+"',
        f'const hegelServerVersion = "{version}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    installer.write_text(text)

    # hegel-go's protocolVersion const (connection.go) is only used in test
    # fixtures, not in any client-enforced version range, so we don't bump it.

    current_url = f"https://github.com/{CORE_REPO}/releases/tag/v{current_version}"
    release_url = f"https://github.com/{CORE_REPO}/releases/tag/v{version}"

    release_md = ROOT / "RELEASE.md"
    release_md.write_text(
        f"RELEASE_TYPE: patch\n\n"
        f"This patch bumps our pinned hegel-core from "
        f"[{current_version}]({current_url}) to [{version}]({release_url}).\n"
    )

    app_id = os.environ["HEGEL_RELEASE_APP_ID"]
    git("config", "user.name", "hegel-release[bot]")
    git("config", "user.email", f"{app_id}+hegel-release[bot]@users.noreply.github.com")

    git("checkout", "-b", "ci/bump-hegel-core")
    git("add", "installer.go", "RELEASE.md")
    git("commit", "-m", f"Bump hegel-core to {version}")
    git("push", "--force", "origin", "ci/bump-hegel-core")

    # Only create a PR if one doesn't already exist for this branch.
    # If one exists, the force-push above already updated it.
    result = subprocess.run(
        ["gh", "pr", "list", "--head", "ci/bump-hegel-core", "--state", "open", "--json", "number"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    title = f"Bump pinned `hegel-core` to `{version}`"
    bump_url = "https://github.com/hegeldev/hegel-go/blob/main/.github/workflows/bump-hegel-core.yml"
    core_url = "https://github.com/hegeldev/hegel-core/blob/main/.github/workflows/ci.yml"
    body = (
        f"This PR bumps our pinned `hegel-core` version to `v{version}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [bump-hegel-core.yml]({bump_url})"
        f" after a trigger by [this hegel-core workflow]({core_url}).*"
    )
    if has_open_pr:
        subprocess.run(
            ["gh", "pr", "edit", "ci/bump-hegel-core", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )
    else:
        subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )


if __name__ == "__main__":
    bump(os.environ["NEW_VERSION"])
