import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
RUST_REPO = "hegeldev/hegel-rust"
BRANCH = "ci/bump-hegel-rust"
CHECKSUMS = ROOT / "internal" / "libhegel" / "checksums.go"
RELEASE_MD = ROOT / "RELEASE.md"

WORKFLOW_URL = (
    "https://github.com/hegeldev/hegel-go/blob/main/.github/workflows/bump-hegel-rust.yml"
)


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=ROOT)


def get_pinned_version() -> str:
    text = CHECKSUMS.read_text()
    m = re.search(r'^const hegelVersion = "([^"]+)"', text, re.MULTILINE)
    assert m is not None, "could not find hegelVersion in checksums.go"
    return m.group(1)


def bump(requested: str) -> None:
    current = get_pinned_version()

    # `just update-checksums` regenerates checksums.go for the target release
    # (empty requested -> latest) and gofmts it. update-checksums.go discovers
    # the resolved version itself, so we read it back rather than trusting the
    # request (which may be empty for a manual latest-bump).
    subprocess.run(["just", "update-checksums", requested], check=True, cwd=ROOT)
    new = get_pinned_version()

    if new == current:
        print(f"Already pinned to v{current}; nothing to do.")
        return

    current_url = f"https://github.com/{RUST_REPO}/releases/tag/v{current}"
    new_url = f"https://github.com/{RUST_REPO}/releases/tag/v{new}"

    RELEASE_MD.write_text(
        "RELEASE_TYPE: patch\n\n"
        f"This patch bumps our pinned libhegel ([hegel-rust]({RUST_REPO})) from "
        f"[{current}]({current_url}) to [{new}]({new_url}).\n"
    )

    app_id = os.environ["HEGEL_RELEASE_APP_ID"]
    git("config", "user.name", "hegel-release[bot]")
    git("config", "user.email", f"{app_id}+hegel-release[bot]@users.noreply.github.com")

    # A fixed branch that we force-push: an already-open PR is updated in place
    # to the newest version rather than stacking up a new PR per release.
    git("checkout", "-B", BRANCH)
    git("add", str(CHECKSUMS), str(RELEASE_MD))
    git("commit", "-m", f"Bump pinned libhegel to {new}")
    git("push", "--force", "origin", BRANCH)

    title = f"Bump pinned `libhegel` to `{new}`"
    body = (
        f"This PR bumps our pinned `libhegel` version to `v{new}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [bump-hegel-rust.yml]({WORKFLOW_URL}).*"
    )

    # Only create a PR if one doesn't already exist for this branch; the
    # force-push above already updated an open PR's contents.
    result = subprocess.run(
        ["gh", "pr", "list", "--head", BRANCH, "--state", "open", "--json", "number"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    if has_open_pr:
        subprocess.run(
            ["gh", "pr", "edit", BRANCH, "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )
    else:
        subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )


if __name__ == "__main__":
    # An optional argument pins that exact version; with none we take the
    # latest. The repository_dispatch trigger passes client_payload.version.
    bump(sys.argv[1] if len(sys.argv) > 1 else "")
