package hegel

// showcase_test.go demonstrates idiomatic Hegel property-based tests.
// These tests verify real properties — every generated value is used in a meaningful assertion.

import (
	"fmt"
	"math"
	"regexp"
	"strings"
	"testing"
	"time"
	"unicode/utf8"
)

// TestAdditionIsCommutative verifies that integer addition is commutative.
func TestAdditionIsCommutative(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		x := GenerateInt(-1000, 1000)
		y := GenerateInt(-1000, 1000)
		if x+y != y+x {
			panic("addition is not commutative")
		}
	}, WithTestCases(50))
}

// TestAbsoluteValueIsNonNegative verifies that |x| >= 0 for all integers.
func TestAbsoluteValueIsNonNegative(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		x := GenerateInt(-1000, 1000)
		abs := x
		if abs < 0 {
			abs = -abs
		}
		if abs < 0 {
			panic("abs(x) is negative")
		}
	}, WithTestCases(50))
}

// TestDoubleNegationIsIdentity verifies that negating a boolean twice gives the original.
func TestDoubleNegationIsIdentity(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		b := GenerateBool()
		notB := !b
		notNotB := !notB
		if notNotB != b {
			panic("double negation is not identity")
		}
	}, WithTestCases(20))
}

// TestEmailContainsAtSymbol demonstrates generating email addresses.
// Every email must contain exactly one "@" separating local and domain parts.
func TestEmailContainsAtSymbol(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		email := Emails().Generate().(string)
		parts := strings.Split(email, "@")
		if len(parts) != 2 {
			panic("email must have exactly one '@': " + email)
		}
		if parts[0] == "" {
			panic("email local-part must not be empty: " + email)
		}
		if parts[1] == "" {
			panic("email domain part must not be empty: " + email)
		}
	}, WithTestCases(50))
}

// TestDateParsingRoundtrip demonstrates that generated dates parse and round-trip correctly.
// This mirrors the Python reference test: date.fromisoformat(date_str).isoformat() == date_str.
func TestDateParsingRoundtrip(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		dateStr := Dates().Generate().(string)
		parsed, err := time.Parse("2006-01-02", dateStr)
		if err != nil {
			panic("date not parseable as YYYY-MM-DD: " + dateStr)
		}
		roundTripped := parsed.Format("2006-01-02")
		if roundTripped != dateStr {
			panic("date round-trip failed: " + dateStr + " != " + roundTripped)
		}
	}, WithTestCases(50))
}

// TestJustAlwaysReturnsConstant demonstrates Just by verifying that every generated
// value is the same constant — a fundamental property of constant generators.
func TestJustAlwaysReturnsConstant(t *testing.T) {
	hegelBinPath(t)
	const expected = "fixed"
	RunHegelTest(t.Name(), func() {
		v := Just(expected).Generate()
		s, ok := v.(string)
		if !ok || s != expected {
			panic(fmt.Sprintf("Just: expected %q, got %v", expected, v))
		}
	}, WithTestCases(30))
}

// TestSampledFromOnlyReturnsListElements demonstrates SampledFrom by verifying that
// every generated value is one of the input elements — no values outside the list.
func TestSampledFromOnlyReturnsListElements(t *testing.T) {
	hegelBinPath(t)
	weekdays := []any{"Mon", "Tue", "Wed", "Thu", "Fri"}
	g, _ := SampledFrom(weekdays)
	validSet := map[string]bool{"Mon": true, "Tue": true, "Wed": true, "Thu": true, "Fri": true}
	RunHegelTest(t.Name(), func() {
		v := g.Generate()
		day, ok := v.(string)
		if !ok || !validSet[day] {
			panic(fmt.Sprintf("SampledFrom: unexpected value %v", v))
		}
	}, WithTestCases(50))
}

// TestFromRegexAllValuesMatchPattern demonstrates FromRegex by verifying that every
// generated string matches the regex pattern — the core property of regex generators.
func TestFromRegexAllValuesMatchPattern(t *testing.T) {
	hegelBinPath(t)
	pattern := `[A-Z]{2,4}`
	re := regexp.MustCompile(`^` + pattern + `$`)
	g := FromRegex(pattern, true)
	RunHegelTest(t.Name(), func() {
		v := g.Generate()
		s, ok := v.(string)
		if !ok {
			panic(fmt.Sprintf("FromRegex: expected string, got %T", v))
		}
		if !re.MatchString(s) {
			panic(fmt.Sprintf("FromRegex: %q does not match pattern %s", s, pattern))
		}
	}, WithTestCases(50))
}

// TestTextLengthBoundsAreRespected demonstrates the Text generator by verifying that
// every generated string has a codepoint count within the specified bounds.
func TestTextLengthBoundsAreRespected(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		s := Text(3, 7).Generate().(string)
		count := utf8.RuneCountInString(s)
		if count < 3 || count > 7 {
			panic(fmt.Sprintf("text: codepoint count %d out of [3, 7]", count))
		}
	}, WithTestCases(50))
}

// TestBinaryLengthBoundsAreRespected demonstrates the Binary generator by verifying that
// every generated byte slice has a length within the specified bounds.
func TestBinaryLengthBoundsAreRespected(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		b := Binary(2, 6).Generate().([]byte)
		if len(b) < 2 || len(b) > 6 {
			panic(fmt.Sprintf("binary: length %d out of [2, 6]", len(b)))
		}
	}, WithTestCases(50))
}

// TestFloatsBoundedExcludesSpecials demonstrates that Floats with explicit bounds
// never produces NaN or Inf when those flags are disabled.
func TestFloatsBoundedExcludesSpecials(t *testing.T) {
	hegelBinPath(t)
	falseBool := false
	RunHegelTest(t.Name(), func() {
		f := Floats(floatPtr(-100.0), floatPtr(100.0), &falseBool, &falseBool, false, false).Generate().(float64)
		if math.IsNaN(f) {
			panic("floats: unexpected NaN with allow_nan=false")
		}
		if math.IsInf(f, 0) {
			panic("floats: unexpected Inf with allow_infinity=false")
		}
		if f < -100.0 || f > 100.0 {
			panic(fmt.Sprintf("floats: %v out of [-100, 100]", f))
		}
	}, WithTestCases(50))
}

// TestBooleansWithHighP demonstrates that with p=1.0, booleans always generates true.
// This is a fundamental property: p=1.0 means probability 1 of true.
func TestBooleansWithHighP(t *testing.T) {
	hegelBinPath(t)
	RunHegelTest(t.Name(), func() {
		b := Booleans(1.0).Generate().(bool)
		if !b {
			panic("booleans(p=1.0): expected always true")
		}
	}, WithTestCases(20))
}

// TestMapDoubledIntegersAreEven demonstrates that mapping integers by doubling
// always produces even numbers — a fundamental arithmetic property.
// Uses BasicGenerator.Map which preserves the schema (single server round-trip).
func TestMapDoubledIntegersAreEven(t *testing.T) {
	hegelBinPath(t)
	doubled := Integers(-50, 50).Map(func(v any) any {
		n, _ := ExtractInt(v)
		return n * 2
	})
	RunHegelTest(t.Name(), func() {
		v := doubled.Generate()
		n, _ := ExtractInt(v)
		if n%2 != 0 {
			panic(fmt.Sprintf("doubled integer must be even, got %d", n))
		}
		if n < -100 || n > 100 {
			panic(fmt.Sprintf("doubled integer must be in [-100,100], got %d", n))
		}
	}, WithTestCases(50))
}

// TestMapChainedTransformsCompose demonstrates that chaining multiple Map calls
// composes the transforms correctly — a fundamental property of function composition.
// integers(1, 10).map(x*x).map(x-1): result is x²-1 for x in [1,10].
// Property: result is always non-negative (since x² >= 1).
func TestMapChainedTransformsCompose(t *testing.T) {
	hegelBinPath(t)
	gen := Integers(1, 10).
		Map(func(v any) any {
			n, _ := ExtractInt(v)
			return n * n // square
		}).
		Map(func(v any) any {
			n, _ := ExtractInt(v)
			return n - 1 // subtract 1
		})
	RunHegelTest(t.Name(), func() {
		v := gen.Generate()
		n, _ := ExtractInt(v)
		// x in [1,10] → x² in [1,100] → x²-1 in [0,99]; always non-negative.
		if n < 0 {
			panic(fmt.Sprintf("map(x²-1) on [1,10]: expected non-negative, got %d", n))
		}
		if n > 99 {
			panic(fmt.Sprintf("map(x²-1) on [1,10]: expected <= 99, got %d", n))
		}
	}, WithTestCases(50))
}
