// Code generated by scripts/update-checksums.go; DO NOT EDIT.
//
// Run `just update-checksums` to pull in the latest hegel-rust release, then
// commit the result.

package libhegel

// hegelVersion is the libhegel version this client expects. The auto-
// downloader fetches the release at this tag from hegel-rust's GitHub
// releases, and [TestLoadLibVersion] asserts that the loaded library
// reports this version.
const hegelVersion = "0.25.0"

// libhegelChecksums maps each downloadable release asset to the expected
// SHA-256 hex digest of its contents for hegelVersion. The digests are baked
// into the source on purpose: fetching a checksum file from the same release
// it is meant to verify provides no integrity guarantee, since a tampered
// release would simply ship a matching checksum. Pinning the digest here means
// the download is verified against a value the attacker cannot influence
// without also compromising this repository.
//
// Only the assets a client can actually request appear here — one per
// supported GOOS/GOARCH, named by libhegelAssetName. Platforms without an
// entry fail the download with a clear "no baked-in checksum" error rather
// than silently skipping verification.
var libhegelChecksums = map[string]string{
	"libhegel-darwin-arm64.dylib": "cbc2ccc591b2308f25b7ba9a9e634387ad7da076ab8c2f7e48149784ef659115",
	"libhegel-linux-amd64.so":     "774c24779ea5df3bd824a0c22bdcdf436031b8300b60a70a6a26a70f28a45776",
	"libhegel-linux-arm64.so":     "945377c7f16d22c6464c8ebec986616a18185d5a8d966bb0df5898f1f183187a",
	"libhegel-windows-amd64.dll":  "dd812053f1f222448c3e7b7d246ad732563d82cb2f7b47bc57eec764c69ea1d6",
	"libhegel-windows-arm64.dll":  "34dbb38d614960498ab16ff3b7ad7984d4496ba28a83acec2c8de71e448ba31e",
}
