// Code generated by scripts/update-checksums.go; DO NOT EDIT.
//
// Run `just update-checksums` to pull in the latest hegel-rust release, then
// commit the result.

package libhegel

// hegelVersion is the libhegel version this client expects. The auto-
// downloader fetches the release at this tag from hegel-rust's GitHub
// releases, and [TestLoadLibVersion] asserts that the loaded library
// reports this version.
const hegelVersion = "0.19.1"

// libhegelChecksums maps each downloadable release asset to the expected
// SHA-256 hex digest of its contents for hegelVersion. The digests are baked
// into the source on purpose: fetching a checksum file from the same release
// it is meant to verify provides no integrity guarantee, since a tampered
// release would simply ship a matching checksum. Pinning the digest here means
// the download is verified against a value the attacker cannot influence
// without also compromising this repository.
//
// Only the assets a client can actually request appear here — one per
// supported GOOS/GOARCH, named by libhegelAssetName. Platforms without an
// entry fail the download with a clear "no baked-in checksum" error rather
// than silently skipping verification.
var libhegelChecksums = map[string]string{
	"libhegel-darwin-arm64.dylib": "63c79c178f9e8d4baa86cb13b012027ffe6bc2ae8a719a200f975bbd51da7fe2",
	"libhegel-linux-amd64.so":     "75e0bf2442d59be5e9e146d684b07abbadf3d1c4474b987d185972af3d1d85b2",
	"libhegel-linux-arm64.so":     "fc8639c8699c918ae66eeb562aac90394ff9f8c2c2c17f10eb9408ddeb6e90c1",
	"libhegel-windows-amd64.dll":  "5976287cbc188b94cbf94622caaca7d42820c7f8134bb4a5a0863792706239a0",
	"libhegel-windows-arm64.dll":  "224ccb9856913a973d0d79ff63d639c562556fbaa722272ce6f05c194c2e919f",
}
