// Code generated by scripts/update-checksums.go; DO NOT EDIT.
//
// Run `just update-checksums` to pull in the latest hegel-rust release, then
// commit the result.

package libhegel

// hegelVersion is the libhegel version this client expects. The auto-
// downloader fetches the release at this tag from hegel-rust's GitHub
// releases, and [TestLoadLibVersion] asserts that the loaded library
// reports this version.
const hegelVersion = "0.17.4"

// libhegelChecksums maps each downloadable release asset to the expected
// SHA-256 hex digest of its contents for hegelVersion. The digests are baked
// into the source on purpose: fetching a checksum file from the same release
// it is meant to verify provides no integrity guarantee, since a tampered
// release would simply ship a matching checksum. Pinning the digest here means
// the download is verified against a value the attacker cannot influence
// without also compromising this repository.
//
// Only the assets a client can actually request appear here — one per
// supported GOOS/GOARCH, named by libhegelAssetName. Platforms without an
// entry fail the download with a clear "no baked-in checksum" error rather
// than silently skipping verification.
var libhegelChecksums = map[string]string{
	"libhegel-darwin-arm64.dylib": "2fe3f3047974c95686ef778d5ca0da09ca3cd497675386a3135859da33134b55",
	"libhegel-linux-amd64.so":     "dd488ed37e3af4a60e717f51a9ded95bd785949ea9f15a06741b93a08cc459d2",
	"libhegel-linux-arm64.so":     "bc9f89c74edb1659199373492a343802ff4403bbbce1f9997fe4a07c53d342f4",
	"libhegel-windows-amd64.dll":  "879c83523d678fe77e091183363d2ebe42858a1bca1b5cd0662cafc0e1e9cda7",
	"libhegel-windows-arm64.dll":  "e6a53a06b8728bb17158e4b5ebc409f38849a313947544db4d1f390afed70229",
}
