// Code generated by "stringer -type=Error,Status,Backend,Verbosity,RunStatus,HealthCheck,Phase,Label -linecomment -output=libhegel_string.go"; DO NOT EDIT.

package libhegel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[E_STOP_TEST - -1]
	_ = x[E_ASSUME - -2]
	_ = x[E_BACKEND - -3]
	_ = x[E_INVALID_HANDLE - -4]
	_ = x[E_INVALID_ARG - -5]
	_ = x[E_ALREADY_COMPLETE - -6]
	_ = x[E_NOT_COMPLETE - -7]
	_ = x[E_INTERNAL - -8]
	_ = x[E_CONCURRENT_USE - -9]
	_ = x[E_RETRY - -10]
}

const _Error_name = "E_RETRYE_CONCURRENT_USEE_INTERNALE_NOT_COMPLETEE_ALREADY_COMPLETEE_INVALID_ARGE_INVALID_HANDLEE_BACKENDE_ASSUMEE_STOP_TESTOK"

var _Error_index = [...]uint8{0, 7, 23, 33, 47, 65, 78, 94, 103, 111, 122, 124}

func (i Error) String() string {
	idx := int(i) - -10
	if i < -10 || idx >= len(_Error_index)-1 {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[idx]:_Error_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS_VALID-0]
	_ = x[STATUS_INVALID-1]
	_ = x[STATUS_OVERRUN-2]
	_ = x[STATUS_INTERESTING-3]
}

const _Status_name = "STATUS_VALIDSTATUS_INVALIDSTATUS_OVERRUNSTATUS_INTERESTING"

var _Status_index = [...]uint8{0, 12, 26, 40, 58}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BACKEND_DEFAULT-1]
	_ = x[BACKEND_URANDOM-2]
}

const _Backend_name = "BACKEND_DEFAULTBACKEND_URANDOM"

var _Backend_index = [...]uint8{0, 15, 30}

func (i Backend) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Backend_index)-1 {
		return "Backend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Backend_name[_Backend_index[idx]:_Backend_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERBOSITY_NORMAL-0]
	_ = x[VERBOSITY_QUIET-1]
	_ = x[VERBOSITY_VERBOSE-2]
	_ = x[VERBOSITY_DEBUG-3]
}

const _Verbosity_name = "VERBOSITY_NORMALVERBOSITY_QUIETVERBOSITY_VERBOSEVERBOSITY_DEBUG"

var _Verbosity_index = [...]uint8{0, 16, 31, 48, 63}

func (i Verbosity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Verbosity_index)-1 {
		return "Verbosity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verbosity_name[_Verbosity_index[idx]:_Verbosity_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RUN_STATUS_PASSED-0]
	_ = x[RUN_STATUS_FAILED-1]
	_ = x[RUN_STATUS_ERROR-2]
	_ = x[RUN_STATUS_FAILED_NONDETERMINISTIC-3]
}

const _RunStatus_name = "RUN_STATUS_PASSEDRUN_STATUS_FAILEDRUN_STATUS_ERRORRUN_STATUS_FAILED_NONDETERMINISTIC"

var _RunStatus_index = [...]uint8{0, 17, 34, 50, 84}

func (i RunStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunStatus_index)-1 {
		return "RunStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunStatus_name[_RunStatus_index[idx]:_RunStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HC_FILTER_TOO_MUCH-1]
	_ = x[HC_TOO_SLOW-2]
	_ = x[HC_TEST_CASES_TOO_LARGE-4]
	_ = x[HC_LARGE_INITIAL_TEST_CASE-8]
}

const (
	_HealthCheck_name_0 = "filter_too_muchtoo_slow"
	_HealthCheck_name_1 = "test_cases_too_large"
	_HealthCheck_name_2 = "large_initial_test_case"
)

var (
	_HealthCheck_index_0 = [...]uint8{0, 15, 23}
)

func (i HealthCheck) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _HealthCheck_name_0[_HealthCheck_index_0[i]:_HealthCheck_index_0[i+1]]
	case i == 4:
		return _HealthCheck_name_1
	case i == 8:
		return _HealthCheck_name_2
	default:
		return "HealthCheck(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHASE_EXPLICIT-1]
	_ = x[PHASE_REUSE-2]
	_ = x[PHASE_GENERATE-4]
	_ = x[PHASE_TARGET-8]
	_ = x[PHASE_SHRINK-16]
	_ = x[PHASE_ALL-31]
}

const (
	_Phase_name_0 = "PHASE_EXPLICITPHASE_REUSE"
	_Phase_name_1 = "PHASE_GENERATE"
	_Phase_name_2 = "PHASE_TARGET"
	_Phase_name_3 = "PHASE_SHRINK"
	_Phase_name_4 = "PHASE_ALL"
)

var (
	_Phase_index_0 = [...]uint8{0, 14, 25}
)

func (i Phase) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Phase_name_0[_Phase_index_0[i]:_Phase_index_0[i+1]]
	case i == 4:
		return _Phase_name_1
	case i == 8:
		return _Phase_name_2
	case i == 16:
		return _Phase_name_3
	case i == 31:
		return _Phase_name_4
	default:
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LABEL_LIST-2801019076836953716]
	_ = x[LABEL_LIST_ELEMENT-17869309736790133779]
	_ = x[LABEL_SET-5865200140810442820]
	_ = x[LABEL_SET_ELEMENT-16914690668663268067]
	_ = x[LABEL_MAP-5590808215537288722]
	_ = x[LABEL_MAP_ENTRY-13638593894540015217]
	_ = x[LABEL_TUPLE-2606859103638815834]
	_ = x[LABEL_ONE_OF-1646594287079187632]
	_ = x[LABEL_OPTIONAL-2831377877786720272]
	_ = x[LABEL_FIXED_DICT-3378490235687764091]
	_ = x[LABEL_FLAT_MAP-17589065948398953226]
	_ = x[LABEL_FILTER-524933089993392430]
	_ = x[LABEL_MAPPED-5332314179289137799]
	_ = x[LABEL_SAMPLED_FROM-11188332258118722663]
	_ = x[LABEL_ENUM_VARIANT-13694910494764798659]
	_ = x[LABEL_FEATURE_FLAG-6375675817545272289]
	_ = x[LABEL_REGEX-14852562533782475579]
	_ = x[LABEL_EMAIL-14835994298877507076]
	_ = x[LABEL_URL-1985340265217183813]
	_ = x[LABEL_DOMAIN-17058301915510424728]
	_ = x[LABEL_DATE-16402304753201470568]
	_ = x[LABEL_TIME-5300822282277835853]
	_ = x[LABEL_DATETIME-14221666525246718433]
	_ = x[LABEL_UUID-9890585168375486663]
	_ = x[LABEL_IP_ADDRESS-14857737725346391278]
	_ = x[LABEL_INTEGER-2322818162524834726]
	_ = x[LABEL_FLOAT-10378366191659462670]
	_ = x[LABEL_BOOLEAN-15851258441080226520]
	_ = x[LABEL_BYTES-5319699480805377615]
	_ = x[LABEL_STRING-14117235223881480941]
	_ = x[LABEL_STATEFUL_RULE-13973930604097954071]
	_ = x[LABEL_FRESH_ID-593156558150809056]
	_ = x[LABEL_SET_CHOICE-9316085528689457538]
	_ = x[LABEL_CONCURRENCY-12925656410196983251]
	_ = x[LABEL_RECURSIVE-52359896170306008]
	_ = x[LABEL_COMPOSITE-18247645122289998975]
}

const _Label_name = "hegel.go.recursivehegel.go.filterhegel.go.fresh_idhegel.go.one_ofhegel.go.urlhegel.go.integerhegel.go.tuplehegel.go.listhegel.go.optionalhegel.go.fixed_dicthegel.go.timehegel.go.byteshegel.go.mappedhegel.go.maphegel.go.sethegel.go.feature_flaghegel.go.set_choicehegel.go.uuidhegel.go.floathegel.go.sampled_fromhegel.go.concurrencyhegel.go.map_entryhegel.go.enum_varianthegel.go.stateful_rulehegel.go.stringhegel.go.datetimehegel.go.emailhegel.go.regexhegel.go.ip_addresshegel.go.booleanhegel.go.datehegel.go.set_elementhegel.go.domainhegel.go.flat_maphegel.go.list_elementhegel.go.composite"

var _Label_map = map[Label]string{
	52359896170306008:    _Label_name[0:18],
	524933089993392430:   _Label_name[18:33],
	593156558150809056:   _Label_name[33:50],
	1646594287079187632:  _Label_name[50:65],
	1985340265217183813:  _Label_name[65:77],
	2322818162524834726:  _Label_name[77:93],
	2606859103638815834:  _Label_name[93:107],
	2801019076836953716:  _Label_name[107:120],
	2831377877786720272:  _Label_name[120:137],
	3378490235687764091:  _Label_name[137:156],
	5300822282277835853:  _Label_name[156:169],
	5319699480805377615:  _Label_name[169:183],
	5332314179289137799:  _Label_name[183:198],
	5590808215537288722:  _Label_name[198:210],
	5865200140810442820:  _Label_name[210:222],
	6375675817545272289:  _Label_name[222:243],
	9316085528689457538:  _Label_name[243:262],
	9890585168375486663:  _Label_name[262:275],
	10378366191659462670: _Label_name[275:289],
	11188332258118722663: _Label_name[289:310],
	12925656410196983251: _Label_name[310:330],
	13638593894540015217: _Label_name[330:348],
	13694910494764798659: _Label_name[348:369],
	13973930604097954071: _Label_name[369:391],
	14117235223881480941: _Label_name[391:406],
	14221666525246718433: _Label_name[406:423],
	14835994298877507076: _Label_name[423:437],
	14852562533782475579: _Label_name[437:451],
	14857737725346391278: _Label_name[451:470],
	15851258441080226520: _Label_name[470:486],
	16402304753201470568: _Label_name[486:499],
	16914690668663268067: _Label_name[499:519],
	17058301915510424728: _Label_name[519:534],
	17589065948398953226: _Label_name[534:551],
	17869309736790133779: _Label_name[551:572],
	18247645122289998975: _Label_name[572:590],
}

func (i Label) String() string {
	if str, ok := _Label_map[i]; ok {
		return str
	}
	return "Label(" + strconv.FormatInt(int64(i), 10) + ")"
}
