// Code generated by "stringer -type=Error,Status,Mode,Backend,Verbosity,RunStatus,HealthCheck,Phase,Label -linecomment -output=libhegel_string.go"; DO NOT EDIT.

package libhegel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[E_STOP_TEST - -1]
	_ = x[E_ASSUME - -2]
	_ = x[E_BACKEND - -3]
	_ = x[E_INVALID_HANDLE - -4]
	_ = x[E_INVALID_ARG - -5]
	_ = x[E_ALREADY_COMPLETE - -6]
	_ = x[E_NOT_COMPLETE - -7]
	_ = x[E_INTERNAL - -8]
	_ = x[E_CONCURRENT_USE - -9]
}

const _Error_name = "E_CONCURRENT_USEE_INTERNALE_NOT_COMPLETEE_ALREADY_COMPLETEE_INVALID_ARGE_INVALID_HANDLEE_BACKENDE_ASSUMEE_STOP_TESTOK"

var _Error_index = [...]uint8{0, 16, 26, 40, 58, 71, 87, 96, 104, 115, 117}

func (i Error) String() string {
	idx := int(i) - -9
	if i < -9 || idx >= len(_Error_index)-1 {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[idx]:_Error_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS_VALID-0]
	_ = x[STATUS_INVALID-1]
	_ = x[STATUS_OVERRUN-2]
	_ = x[STATUS_INTERESTING-3]
}

const _Status_name = "STATUS_VALIDSTATUS_INVALIDSTATUS_OVERRUNSTATUS_INTERESTING"

var _Status_index = [...]uint8{0, 12, 26, 40, 58}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MODE_TEST_RUN-0]
	_ = x[MODE_SINGLE_TEST_CASE-1]
}

const _Mode_name = "MODE_TEST_RUNMODE_SINGLE_TEST_CASE"

var _Mode_index = [...]uint8{0, 13, 34}

func (i Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BACKEND_AUTO-0]
	_ = x[BACKEND_DEFAULT-1]
	_ = x[BACKEND_URANDOM-2]
}

const _Backend_name = "BACKEND_AUTOBACKEND_DEFAULTBACKEND_URANDOM"

var _Backend_index = [...]uint8{0, 12, 27, 42}

func (i Backend) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Backend_index)-1 {
		return "Backend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Backend_name[_Backend_index[idx]:_Backend_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERBOSITY_QUIET-0]
	_ = x[VERBOSITY_NORMAL-1]
	_ = x[VERBOSITY_VERBOSE-2]
	_ = x[VERBOSITY_DEBUG-3]
}

const _Verbosity_name = "VERBOSITY_QUIETVERBOSITY_NORMALVERBOSITY_VERBOSEVERBOSITY_DEBUG"

var _Verbosity_index = [...]uint8{0, 15, 31, 48, 63}

func (i Verbosity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Verbosity_index)-1 {
		return "Verbosity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verbosity_name[_Verbosity_index[idx]:_Verbosity_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RUN_STATUS_PASSED-0]
	_ = x[RUN_STATUS_FAILED-1]
	_ = x[RUN_STATUS_ERROR-2]
}

const _RunStatus_name = "RUN_STATUS_PASSEDRUN_STATUS_FAILEDRUN_STATUS_ERROR"

var _RunStatus_index = [...]uint8{0, 17, 34, 50}

func (i RunStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunStatus_index)-1 {
		return "RunStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunStatus_name[_RunStatus_index[idx]:_RunStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HC_FILTER_TOO_MUCH-1]
	_ = x[HC_TOO_SLOW-2]
	_ = x[HC_TEST_CASES_TOO_LARGE-4]
	_ = x[HC_LARGE_INITIAL_TEST_CASE-8]
}

const (
	_HealthCheck_name_0 = "filter_too_muchtoo_slow"
	_HealthCheck_name_1 = "test_cases_too_large"
	_HealthCheck_name_2 = "large_initial_test_case"
)

var (
	_HealthCheck_index_0 = [...]uint8{0, 15, 23}
)

func (i HealthCheck) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _HealthCheck_name_0[_HealthCheck_index_0[i]:_HealthCheck_index_0[i+1]]
	case i == 4:
		return _HealthCheck_name_1
	case i == 8:
		return _HealthCheck_name_2
	default:
		return "HealthCheck(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHASE_EXPLICIT-1]
	_ = x[PHASE_REUSE-2]
	_ = x[PHASE_GENERATE-4]
	_ = x[PHASE_TARGET-8]
	_ = x[PHASE_SHRINK-16]
}

const (
	_Phase_name_0 = "PHASE_EXPLICITPHASE_REUSE"
	_Phase_name_1 = "PHASE_GENERATE"
	_Phase_name_2 = "PHASE_TARGET"
	_Phase_name_3 = "PHASE_SHRINK"
)

var (
	_Phase_index_0 = [...]uint8{0, 14, 25}
)

func (i Phase) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Phase_name_0[_Phase_index_0[i]:_Phase_index_0[i+1]]
	case i == 4:
		return _Phase_name_1
	case i == 8:
		return _Phase_name_2
	case i == 16:
		return _Phase_name_3
	default:
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LABEL_LIST-1]
	_ = x[LABEL_LIST_ELEMENT-2]
	_ = x[LABEL_SET-3]
	_ = x[LABEL_SET_ELEMENT-4]
	_ = x[LABEL_MAP-5]
	_ = x[LABEL_MAP_ENTRY-6]
	_ = x[LABEL_TUPLE-7]
	_ = x[LABEL_ONE_OF-8]
	_ = x[LABEL_OPTIONAL-9]
	_ = x[LABEL_FIXED_DICT-10]
	_ = x[LABEL_FLAT_MAP-11]
	_ = x[LABEL_FILTER-12]
	_ = x[LABEL_MAPPED-13]
	_ = x[LABEL_SAMPLED_FROM-14]
	_ = x[LABEL_ENUM_VARIANT-15]
	_ = x[LABEL_FEATURE_FLAG-16]
	_ = x[LABEL_REGEX-17]
	_ = x[LABEL_EMAIL-18]
	_ = x[LABEL_URL-19]
	_ = x[LABEL_DOMAIN-20]
	_ = x[LABEL_DATE-21]
	_ = x[LABEL_TIME-22]
	_ = x[LABEL_DATETIME-23]
	_ = x[LABEL_UUID-24]
	_ = x[LABEL_IP_ADDRESS-25]
	_ = x[LABEL_INTEGER-26]
	_ = x[LABEL_FLOAT-27]
	_ = x[LABEL_BOOLEAN-28]
	_ = x[LABEL_BYTES-29]
	_ = x[LABEL_STRING-30]
	_ = x[LABEL_STATEFUL_RULE-31]
	_ = x[LABEL_COMPOSITE-32]
	_ = x[LABEL_STATEFUL-33]
}

const _Label_name = "LABEL_LISTLABEL_LIST_ELEMENTLABEL_SETLABEL_SET_ELEMENTLABEL_MAPLABEL_MAP_ENTRYLABEL_TUPLELABEL_ONE_OFLABEL_OPTIONALLABEL_FIXED_DICTLABEL_FLAT_MAPLABEL_FILTERLABEL_MAPPEDLABEL_SAMPLED_FROMLABEL_ENUM_VARIANTLABEL_FEATURE_FLAGLABEL_REGEXLABEL_EMAILLABEL_URLLABEL_DOMAINLABEL_DATELABEL_TIMELABEL_DATETIMELABEL_UUIDLABEL_IP_ADDRESSLABEL_INTEGERLABEL_FLOATLABEL_BOOLEANLABEL_BYTESLABEL_STRINGLABEL_STATEFUL_RULELABEL_COMPOSITELABEL_STATEFUL"

var _Label_index = [...]uint16{0, 10, 28, 37, 54, 63, 78, 89, 101, 115, 131, 145, 157, 169, 187, 205, 223, 234, 245, 254, 266, 276, 286, 300, 310, 326, 339, 350, 363, 374, 386, 405, 420, 434}

func (i Label) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Label_index)-1 {
		return "Label(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Label_name[_Label_index[idx]:_Label_index[idx+1]]
}
