// Code generated by scripts/vendor-libhegel.go; DO NOT EDIT.
//
// Run `just vendor-libhegel` to vendor the latest hegel-rust release (this
// constant plus the binaries under libs/), then commit the result.

package libhegel

// hegelVersion is the libhegel version vendored into this client. The binaries
// embedded from libs/ are built from this hegel-rust release, and
// [TestLoadLibVersion] asserts that the loaded library reports this version.
const hegelVersion = "0.30.4"
