//go:build ignore

// Command gen-timezones regenerates timezones_data.go, the list of IANA time
// zone names that hegel.Timezones draws from.
//
// The names come from the zoneinfo.zip bundled with the Go toolchain running
// this command, which is the same data time/tzdata embeds, so every name
// resolves through time.LoadLocation even on hosts without a system zone
// database. "UTC" is placed first so it is the value failing examples shrink
// toward; the remaining names are sorted. "Factory" is dropped: it is the tz
// database's placeholder for an unconfigured host, not a real zone.
//
// Usage:
//
//	go generate ./...
//
// or, equivalently:
//
//	go run scripts/gen-timezones.go
package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
)

const output = "timezones_data.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-timezones:", err)
		os.Exit(1)
	}
}

func run() error {
	out, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return fmt.Errorf("go env GOROOT: %w", err)
	}
	goroot := strings.TrimSpace(string(out))

	names, err := zoneNames(filepath.Join(goroot, "lib", "time", "zoneinfo.zip"))
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by scripts/gen-timezones.go from the %s zoneinfo.zip%s; DO NOT EDIT.\n\n",
		runtime.Version(), tzdataVersion(goroot))
	buf.WriteString("package hegel\n\n")
	buf.WriteString("// timezoneNames lists the IANA time zone names [Timezones] draws from. UTC\n")
	buf.WriteString("// comes first so failing examples shrink toward it; the rest are sorted.\n")
	buf.WriteString("var timezoneNames = []string{\n")
	for _, name := range names {
		fmt.Fprintf(&buf, "\t%q,\n", name)
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	if err := os.WriteFile(output, src, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d zones)\n", output, len(names))
	return nil
}

// zoneNames returns every zone in the archive except Factory, sorted, with
// UTC moved to the front.
func zoneNames(zipPath string) ([]string, error) {
	r, err := zip.OpenReader(zipPath)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", zipPath, err)
	}
	defer r.Close()

	var names []string
	for _, f := range r.File {
		if strings.HasSuffix(f.Name, "/") || f.Name == "Factory" || f.Name == "UTC" {
			continue
		}
		names = append(names, f.Name)
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("no zones found in %s", zipPath)
	}
	sort.Strings(names)
	return append([]string{"UTC"}, names...), nil
}

// tzdataVersion reports the tz database release the toolchain bundles, as
// recorded by lib/time/update.bash, formatted for the generated header.
// Returns "" when the script is not available.
func tzdataVersion(goroot string) string {
	script, err := os.ReadFile(filepath.Join(goroot, "lib", "time", "update.bash"))
	if err != nil {
		return ""
	}
	m := regexp.MustCompile(`(?m)^DATA=(\S+)`).FindSubmatch(script)
	if m == nil {
		return ""
	}
	return fmt.Sprintf(" (tzdata %s)", m[1])
}
