//go:build ignore

// Command update-checksums regenerates the baked-in libhegel checksum table.
//
// The downloader verifies each fetched libhegel artifact against a SHA-256
// digest compiled into the source (see libhegelChecksums). Fetching a checksum
// file from the same release it verifies would be pointless — a tampered
// release would ship a matching checksum — so the digests live in the
// repository instead.
//
// This program queries a hegel-rust GitHub release (the latest by default, or
// the one named by -version) and reads the SHA-256 digest GitHub records for
// each client-requestable artifact (one per supported GOOS/GOARCH, i.e. the
// .so/.dylib/.dll assets), then writes a fresh, generated source file pinning
// both the release version (hegelVersion) and the per-asset checksums. Run it
// to bump the pinned release, then commit the result.
//
// Usage:
//
//	go run scripts/update-checksums.go [-version <v>] -- <output-file>
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const repo = "hegeldev/hegel-rust"

// clientAssetRE matches the assets a client can actually request:
// libhegelAssetName() yields a .so (Linux/other), .dylib (darwin), or .dll
// (windows) name. The .sha256 sidecar assets are irrelevant to runtime
// verification (GitHub records a digest for every asset) and are excluded.
var clientAssetRE = regexp.MustCompile(`^libhegel-[a-z0-9]+-[a-z0-9]+\.(so|dylib|dll)$`)

// release queries a hegel-rust release and returns its version (the tag with
// any leading "v" stripped) along with the SHA-256 digest GitHub records for
// each client-requestable asset, keyed by asset name. An empty want selects the
// latest release; otherwise the release tagged v<want> is fetched. Trusting
// GitHub's recorded digest is sound: it is computed server-side from the stored
// bytes, so it matches what the downloader will fetch over the same channel.
func release(want string) (version string, checksums map[string]string, err error) {
	args := []string{"release", "view"}
	if want != "" {
		// GitHub release tags are v-prefixed; accept a bare or v-prefixed want.
		args = append(args, "v"+strings.TrimPrefix(want, "v"))
	}
	args = append(args, "--repo", repo, "--json", "tagName,assets")

	out, err := exec.Command("gh", args...).Output()
	if err != nil {
		// gh writes the real reason (e.g. "HTTP 401", "release not found") to
		// stderr; .Output() stashes it in *exec.ExitError.Stderr but the error
		// string alone is just "exit status N". Surface it so failures are
		// diagnosable instead of opaque.
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && len(exitErr.Stderr) > 0 {
			return "", nil, fmt.Errorf("gh release view: %w: %s", err, strings.TrimSpace(string(exitErr.Stderr)))
		}
		return "", nil, fmt.Errorf("gh release view: %w", err)
	}

	var rel struct {
		TagName string `json:"tagName"`
		Assets  []struct {
			Name   string `json:"name"`
			Digest string `json:"digest"`
		} `json:"assets"`
	}
	if err := json.Unmarshal(out, &rel); err != nil {
		return "", nil, fmt.Errorf("parse gh release view output: %w", err)
	}

	checksums = make(map[string]string)
	for _, a := range rel.Assets {
		if !clientAssetRE.MatchString(a.Name) {
			continue
		}
		hex, ok := strings.CutPrefix(a.Digest, "sha256:")
		if !ok {
			return "", nil, fmt.Errorf("asset %s: expected a sha256: digest, got %q", a.Name, a.Digest)
		}
		checksums[a.Name] = hex
	}
	version = strings.TrimPrefix(rel.TagName, "v")
	if want != "" && version != strings.TrimPrefix(want, "v") {
		return "", nil, fmt.Errorf("requested release v%s but got tag %q", strings.TrimPrefix(want, "v"), rel.TagName)
	}
	return version, checksums, nil
}

// fileTemplate is the generated checksums source file. The %s placeholders are
// the release version and the formatted map entries; gofmt (run by
// `just update-checksums`) aligns the map afterward.
const fileTemplate = `// Code generated by scripts/update-checksums.go; DO NOT EDIT.
//
// Run ` + "`just update-checksums`" + ` to pull in the latest hegel-rust release, then
// commit the result.

package libhegel

// hegelVersion is the libhegel version this client expects. The auto-
// downloader fetches the release at this tag from hegel-rust's GitHub
// releases, and [TestLoadLibVersion] asserts that the loaded library
// reports this version.
const hegelVersion = %q

// libhegelChecksums maps each downloadable release asset to the expected
// SHA-256 hex digest of its contents for hegelVersion. The digests are baked
// into the source on purpose: fetching a checksum file from the same release
// it is meant to verify provides no integrity guarantee, since a tampered
// release would simply ship a matching checksum. Pinning the digest here means
// the download is verified against a value the attacker cannot influence
// without also compromising this repository.
//
// Only the assets a client can actually request appear here — one per
// supported GOOS/GOARCH, named by libhegelAssetName. Platforms without an
// entry fail the download with a clear "no baked-in checksum" error rather
// than silently skipping verification.
var libhegelChecksums = map[string]string{
%s}
`

// render produces the full contents of the generated checksums source file.
func render(version string, checksums map[string]string) string {
	names := make([]string, 0, len(checksums))
	for name := range checksums {
		names = append(names, name)
	}
	sort.Strings(names)

	var entries strings.Builder
	for _, name := range names {
		fmt.Fprintf(&entries, "\t%q: %q,\n", name, checksums[name])
	}
	return fmt.Sprintf(fileTemplate, version, entries.String())
}

func run() error {
	// An empty -version selects the latest release; otherwise the named release
	// (v-prefixed or not) is pinned. The repository_dispatch bump workflow
	// passes the exact released version so a later release can't race in.
	want := flag.String("version", "", "release version to pin (empty selects the latest)")

	// The output filename ends in .go, which `go run` would otherwise treat as
	// another source file, so callers separate it with `--`
	// (`go run scripts/update-checksums.go -- internal/libhegel/checksums.go`).
	// flag.Parse strips that terminator for us.
	flag.Parse()
	if flag.NArg() != 1 {
		return fmt.Errorf("usage: %s [-version <v>] -- <output-file>", filepath.Base(os.Args[0]))
	}
	output := flag.Arg(0)

	version, checksums, err := release(*want)
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "libhegel release: v%s\n", version)
	if len(checksums) == 0 {
		return fmt.Errorf("no .so/.dylib/.dll assets found in release v%s", version)
	}

	if err := os.WriteFile(output, []byte(render(version, checksums)), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %d checksum(s) to %s\n", len(checksums), output)
	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
