//go:build ignore

// Command vendor-libhegel vendors a hegel-rust release into the repo.
//
// The pre-compiled libhegel artifacts are checked into internal/libhegel/libs
// (stored via git-lfs) and go:embed'd into the client at build time, so there
// is no runtime download. This program queries a hegel-rust GitHub release (the
// latest by default, or the one named by -version), downloads each
// client-requestable artifact (one per supported GOOS/GOARCH, i.e. the
// .so/.dylib/.dll assets) into the libs dir — verifying each against the
// SHA-256 digest GitHub records — and rewrites internal/libhegel/version.go to
// pin the resolved version. Run it to bump the vendored release, then commit
// the result (with git-lfs installed).
//
// Usage:
//
//	go run scripts/vendor-libhegel.go [-version <v>]
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const repo = "hegeldev/hegel-rust"

// libsDir and versionFile are written relative to the current working
// directory, which `just vendor-libhegel` sets to the repo root.
const (
	libsDir     = "internal/libhegel/libs"
	versionFile = "internal/libhegel/version.go"
)

// clientAssetRE matches the assets a client can actually request: a .so
// (Linux/other), .dylib (darwin), or .dll (windows) name. The .sha256 sidecar
// assets are excluded — GitHub records a digest for every asset, which we use
// directly.
var clientAssetRE = regexp.MustCompile(`^libhegel-[a-z0-9]+-[a-z0-9]+\.(so|dylib|dll)$`)

type asset struct {
	Name   string `json:"name"`
	Digest string `json:"digest"`
}

// release queries a hegel-rust release and returns its version (the tag with
// any leading "v" stripped) along with the client-requestable assets. An empty
// want selects the latest release; otherwise the release tagged v<want> is
// fetched.
func release(want string) (version string, assets []asset, err error) {
	args := []string{"release", "view"}
	if want != "" {
		// GitHub release tags are v-prefixed; accept a bare or v-prefixed want.
		args = append(args, "v"+strings.TrimPrefix(want, "v"))
	}
	args = append(args, "--repo", repo, "--json", "tagName,assets")

	out, err := exec.Command("gh", args...).Output()
	if err != nil {
		// gh writes the real reason (e.g. "HTTP 401", "release not found") to
		// stderr; .Output() stashes it in *exec.ExitError.Stderr but the error
		// string alone is just "exit status N". Surface it so failures are
		// diagnosable instead of opaque.
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && len(exitErr.Stderr) > 0 {
			return "", nil, fmt.Errorf("gh release view: %w: %s", err, strings.TrimSpace(string(exitErr.Stderr)))
		}
		return "", nil, fmt.Errorf("gh release view: %w", err)
	}

	var rel struct {
		TagName string  `json:"tagName"`
		Assets  []asset `json:"assets"`
	}
	if err := json.Unmarshal(out, &rel); err != nil {
		return "", nil, fmt.Errorf("parse gh release view output: %w", err)
	}

	for _, a := range rel.Assets {
		if clientAssetRE.MatchString(a.Name) {
			assets = append(assets, a)
		}
	}
	version = strings.TrimPrefix(rel.TagName, "v")
	if want != "" && version != strings.TrimPrefix(want, "v") {
		return "", nil, fmt.Errorf("requested release v%s but got tag %q", strings.TrimPrefix(want, "v"), rel.TagName)
	}
	return version, assets, nil
}

// download fetches a single asset from release v<version> into libsDir and
// verifies its contents against the SHA-256 digest GitHub recorded for it.
func download(version string, a asset) error {
	wantHex, ok := strings.CutPrefix(a.Digest, "sha256:")
	if !ok {
		return fmt.Errorf("asset %s: expected a sha256: digest, got %q", a.Name, a.Digest)
	}

	dest := filepath.Join(libsDir, a.Name)
	cmd := exec.Command("gh", "release", "download", "v"+version,
		"--repo", repo, "--pattern", a.Name, "--dir", libsDir, "--clobber")
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("gh release download %s: %w", a.Name, err)
	}

	got, err := os.ReadFile(dest)
	if err != nil {
		return err
	}
	gotHex := hex.EncodeToString(sha256Sum(got))
	if gotHex != wantHex {
		return fmt.Errorf("checksum mismatch for %s: got %s, want %s", a.Name, gotHex, wantHex)
	}
	return nil
}

func sha256Sum(b []byte) []byte {
	h := sha256.Sum256(b)
	return h[:]
}

// versionTemplate is the generated version.go file.
const versionTemplate = `// Code generated by scripts/vendor-libhegel.go; DO NOT EDIT.
//
// Run ` + "`just vendor-libhegel`" + ` to vendor the latest hegel-rust release (this
// constant plus the binaries under libs/), then commit the result.

package libhegel

// hegelVersion is the libhegel version vendored into this client. The binaries
// embedded from libs/ are built from this hegel-rust release, and
// [TestLoadLibVersion] asserts that the loaded library reports this version.
const hegelVersion = %q
`

func run() error {
	// An empty -version selects the latest release; otherwise the named release
	// (v-prefixed or not) is pinned. The repository_dispatch bump workflow
	// passes the exact released version so a later release can't race in.
	want := flag.String("version", "", "release version to vendor (empty selects the latest)")
	flag.Parse()

	version, assets, err := release(*want)
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "libhegel release: v%s\n", version)
	if len(assets) == 0 {
		return fmt.Errorf("no .so/.dylib/.dll assets found in release v%s", version)
	}

	if err := os.MkdirAll(libsDir, 0o755); err != nil {
		return err
	}
	sort.Slice(assets, func(i, j int) bool { return assets[i].Name < assets[j].Name })
	wanted := make(map[string]struct{}, len(assets))
	for _, a := range assets {
		wanted[a.Name] = struct{}{}
		if err := download(version, a); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "vendored %s\n", a.Name)
	}
	entries, err := os.ReadDir(libsDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if !clientAssetRE.MatchString(name) {
			continue
		}
		if _, ok := wanted[name]; ok {
			continue
		}
		if err := os.Remove(filepath.Join(libsDir, name)); err != nil {
			return fmt.Errorf("remove stale asset %s: %w", name, err)
		}
		fmt.Fprintf(os.Stderr, "removed stale %s\n", name)
	}

	if err := os.WriteFile(versionFile, []byte(fmt.Sprintf(versionTemplate, version)), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %d artifact(s) to %s and pinned %s\n", len(assets), libsDir, versionFile)
	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
